### ISSUE TITLE
Add `Qobj` and `tensor`

### ISSUE THREAD

**Issue by ytdHuang** [albertomercurio/QuPhys.jl#14]
To make the syntax more similar to `QuTiP`, I suggest to add the following function support:

- [x] `Qobj(A; kwargs...) = QuantumObject(A; kwargs...)` : This is just for us to create `QuantumObject` in a lazy way (and more similar to `QuTiP`). (f3c95b52822e5d3a2266bf3ed6542e0ad98eb103)
- [x] `tensor(A...) = kron(A...)` : does the same thing as `kron` (9949e380d75ffd5ce9daa02d02c96d1294b1c9a5)
- [x] `⊗(A, B) = kron(A, B)` : take advantage of `QuantumOptics` (9949e380d75ffd5ce9daa02d02c96d1294b1c9a5)

The last support allows us to express `tensor(A, B, C)` as `A ⊗ B ⊗ C`.

If @albertomercurio agrees with this, I can make a PR for this issue.

**Comment by albertomercurio** [comment]
Thank you for submitting this issue.

The proposed changes are reasonable. We can even try to change all QuantumObjects to Qobj, which could be implemented using a simple ctrl+f and then substituting. In this way, we will never deal with QuantumObject anymore.

**Comment by ytdHuang** [comment]
> Thank you for submitting this issue.
> 
> The proposed changes are reasonable. We can even try to change all QuantumObjects to Qobj, which could be implemented using a simple ctrl+f and then substituting. In this way, we will never deal with QuantumObject anymore.

I have made a PR as shown above.

For the substitution of `QuantumObject` to `Qobj`, I didn't do this in the beginning because `Julia` language's naming rule prefer not to use the abbreviation.
In this PR, the new function is really defined as:
```julia
Qobj(A; kwargs...) = QuantumObject(A; kwargs...)
```
That means it is just passing all the args to `QuantumObject()` directly, and `QuantumObject()` will still handle all the types and other stuffs.

For me, I think defining `Qobj` is convenient, and `QuantumObject` looks nice and clear. So I like them both~

**Comment by albertomercurio** [comment]
I agree with you. Let's merge it with with both of them.
